#!/usr/bin/env bash
# installs nginx and sets up a web server
#+ server listens on port 80 and returns
#+ a page containing "Hello World!" when
#+ queried with a curl GET request

echo -e "Updating and Installing nginx\n"
sudo apt-get update
sudo apt-get install -y nginx

echo -e "\nSetting up...\n"

sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default

touch /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html

echo "server {
		listen 80;
		listen [::]:80;
		root /var/www/html;
		index index.html

}" > /etc/nginx/sites-available/default

sudo service nginx start
