#!/usr/bin/env bash
# installs nginx and sets up a web server
#+ server listens on port 80 and returns
#+ a page containing "Hello World!" when
#+ queried with a curl GET request

echo -e "Updating and Installing nginx\n"
sudo apt-get update
sudo apt-get install -y nginx

echo -e "\nSetting up...\n"
sudo service nginx start

sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/bosm.tech/html
sudo chown -R "$USER":"$USER" /var/www/bosm.tech/html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/
sudo chown -R "$USEr":"$USER" /etc/nginx/sites-enabled/
sudo chmod -R 755 /var/www

touch /var/www/bosm.tech/html/index.html
echo 'Hello World!' > /var/www/bosm.tech/html/index.html

#creating the server block
touch /etc/nginx/sites-available/bosm.tech
echo "server {
		listen 80;
		listen [::]:80;

		root /var/www/bosm.tech/html;

		server_name bosm.tech www.bosm.tech;

		location / {
			try_files $uri $uri/ =404;
		}
}" > /etc/nginx/sites-available/bosm.tech

#enabling server blocks
sudo ln -s /etc/nginx/sites-available/bosm.tech /etc/nginx/sites-enabled/

sudo service nginx restart
