#!/usr/bin/env bash
# redirection feature added

echo -e "Updating and Installing nginx\n"
sudo apt-get update
sudo apt-get install -y nginx

echo -e "\nSetting up...\n"
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www


echo -e "Hello World!" > /var/www/html/index.html

echo -e "\tlocation /redirect_me {
\t\treturn 301 https://www.youtube.com/watch?v=hzaQg6jtOnY;
\t}\n" > /tmp/new_config

sed -i '47r /tmp/new_config' /etc/nginx/sites-available/default

sudo service nginx restart
