#!/usr/bin/env bash
# error page added

echo -e "Updating and Installing nginx\n"
sudo apt-get update
sudo apt-get install -y nginx

echo -e "\nSetting up...\n"
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo -e "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/my_404.html

echo -e "\tlocation /redirect_me {
\t\treturn 301 https://www.youtube.com/watch?v=hzaQg6jtOnY;
\t}

\terror_page 404 /my_404.html;
\tlocation = /my_404.html {
\t\troot /usr/share/nginx/html;
\t\tinternal;
\t}\n" > /tmp/new_config

sed -i '47r /tmp/new_config' /etc/nginx/sites-available/default

rm /tmp/new_config

service nginx start
