#!/usr/bin/env bash
# Creates a file containing its PID
# Displays "To infinity and beyond" indefinitely
# Displays "I hate the kill command" when receiving
#+a SIGTERM signal
# Displays "Y U no love me?" when receiving a SIGINT signal
# Deletes the and terminates itself when receiving a
#+SIGQUIT or SIGTERM signal

terminate() {
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid
i=1
while [ $i ];
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminate' SIGTERM
	trap 'terminate' SIGQUIT
done
