#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
#+ displays hours from 0 to 12
#+ displays minutes from 1 to 59
hour=0
min=0
while [ $hour -lt 13 ];
do
	echo "Hour: $hour"
	while [ $min -lt 60 ];
	do
		echo "$min"
		((min++))
	done
	min=0
	((hour++))
done
